export type {
  ProjectBriefContent,
  ProjectBriefDocument,
  ProjectSourceContextDocument,
  ProjectSourceContextStatus,
  ProjectSourceReference,
  ProjectSourceRole,
  SessionAutomation,
  SessionAutomationDetails,
  SessionAutomationEvent,
  SessionAutomationMode,
  SessionAutomationState,
  TerminalAttachment,
  TerminalPathResolution,
  TerminalSession,
  TerminalWorkspaceDescriptor as Project,
  TerminalWorkspaceStatus as WorkspaceStatus,
  TerminalSnapshot,
} from '@dolphin-terminal/protocol';
